openapi: 3.0.0
info:
  title: E-Commerce Bot API
  version: v0.0.1
servers:
  - url: /api
tags:
  - name: Chat

paths:
  /v1/chat:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResult'
          description: Success
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '404':
          description: Resource not found
        '409':
          description: Resource already exists
        '500':
          description: Internal server error
      tags:
        - Chat
      operationId: chat
      parameters:
        - in: header
          name: x-user-id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Chat'
        required: true
      summary: Chat with the bot

components:
  schemas:
    Chat:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    ChatResult:
      type: object
      properties:
        message:
          type: string
        response:
          type: string
      required:
        - message
        - response