openapi: 3.0.0
info:
  title: Test DeFi API
  version: v0.0.1
servers:
  - url: /api
tags:
  - name: DeFi

paths:
  /v1/transactions:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResult'
          description: Success
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '404':
          description: Resource not found
        '409':
          description: Resource already exists
        '500':
          description: Internal server error
      tags:
        - Chat
      operationId: chat
      parameters:
        - in: header
          name: x-user-id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
        required: true
      summary: Chat with the bot

components:
  schemas:
    Transaction:
      type: object
      properties:
        amount:
          type: string
        currency:
          type: string
      required:
        - amount
        - currency

    TransactionResult:
      type: object
      properties:
        hash:
          type: string
        amount:
          type: string
        currency:
          type: string
      required:
        - hash
        - amount
        - currency
